# Chave mestra do sistema (Fernet)
CHAVE_SISTEMA = "Ag__gEi2la99iwk8oHD5O3i6MJMUpfeSNzC9td8_xng="

# Credenciais do Gmail para envio de tokens
GMAIL_USER = "pricardosbrito@gmail.com"
GMAIL_APP_PASSWORD = "bfhs ecmd icxl uwoj"

